name: CI

on: [push, pull_request, release]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2
    - name: Setup 🔌
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Build 🔧
      run: |
        npm ci
        npm run dist
    - name: Test 👨‍🔬
      run: |
        npm test
        npm run audit

  build:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2
    - name: Setup 🔌
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: https://registry.npmjs.org/
    - name: Build 🔧
      run: |
        npm ci
        npm run dist
    - name: Resolving Release Tag 🔍
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Publish 🚀
      run: npm publish --access public --tag $RELEASE_VERSION --dry-run
      env:
        RELEASE_VERSION: ${{steps.vars.outputs.tag}}
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}