name: CI

on: [push, pull_request, release]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run dist
    - run: npm test
    - run: npm run audit

  build:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: https://registry.npmjs.org/
    - run: npm ci
    - run: npm run dist
    - run: npm publish --access public --tag ${{ steps.vars.outputs.tag }} --dry-run
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}